version: "3"

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9003:9003"
    volumes:
      - .:/var/www/html
    environment:
      XDEBUG_MODE: "debug,coverage"
      XDEBUG_CONFIG: "client_host=host.docker.internal"
